uc-cdis/guppy

src/components/ConnectedFilter/index.jsx, src/components/ConnectedFilter/utils.js
Range slider should remember initial min/max value even user drag then. There was a bug in ConnectedFilter and this PR fixes it. 
- fix min and max value for slider
=> fix(slider): fix min and max value for slider

example_config.json, src/server/config.js, src/server/es/index.js
This PR deals with empty config index: if no config index is set, we don't get array index from ES
- deal with empty config index
=> fix(array): deal with empty config index

README.md, devHelper/scripts/commands.sh, src/server/config.js, src/server/logger.js, src/server/middlewares/tierAccessMiddleware/index.js, src/server/utils/utils.js
Add whitelist to tieraccess middleware that will skip encrypting some values. See README for detail. 
- add whitelist to tieraccess middleware that will skip encrypting some values
=> feat(whitelist): add whitelist to tieraccess middleware

src/server/es/index.js
We just decide to change array config format: now array fields are grouped and stored by index as a doc in array config, and we set _id as index name for this doc.
- change array config format to store by doc
=> fix(array): change array config by doc

package-lock.json, package.json, src/server/es/aggs.js
This PR changes aggregation results to be ordered by doc count
- Order aggregation result by doc count
=> fix(order): order aggregation result by doc count

README.md, src/server/config.js
Because the behavior of the existing GEN3_ARBORIST_ENDPOINT defaults to mock if not set, a new OVERRIDE is needed to avoid changing this. If the new OVERRIDE is not set, it defaults to GEN3_ARBORIST_ENDPOINT which might be just http://arborist-service.
See also: https://github.com/uc-cdis/cloud-automation/pull/869/files#diff-ff1d8822f6c3ba09ea41626908560a26
- added `GEN3_ARBORIST_ENDPOINT_OVERRIDE`
=> feat(unity): support customizing Arborist

src/server/es/filter.js
Guppy need to support `!=` op in filter in order to make NIAID HIV app work with Guppy
Please make sure to follow the [DEV guidelines](https://gen3.org/resources/developer/dev-introduction/) before asking for review.
- Support `!=` (is not) op for filter
=> feat/support `is not` op for filter

src/server/__mocks__/mockDataFromES.js, src/server/__mocks__/mockESData/mockNumericAggsGlobalStats.js, src/server/__mocks__/mockESData/mockNumericHistogramFixBinCount.js, src/server/__mocks__/mockESData/mockNumericHistogramFixWidth.js, src/server/__mocks__/mockESData/mockTextAggs.js, src/server/es/__tests__/filter.test.js, src/server/es/filter.js
By default Guppy's elasticsearch aggregation result includes missing data (`aggs_include_missing_data=true`) and missing data were aliased into keyword `no data` (the default `missing_data_alias` value). 
But in this case, selecting `no data` as a facet in data explorer will zeros out the result. Since the `no data` is just a fake alias created by guppy, not an value from an actual es field.
This PR changes the logic of parsing the GQLFilter into ES filter and takes `aggs_include_missing_data` into consideration. If `aggs_include_missing_data` is in using, it will translate any GQLFilter that contains `missing_data_alias` into appropriate ES query 
Please make sure to follow the [DEV guidelines](https://gen3.org/resources/developer/dev-introduction/) before asking for review.
- Correctly …
=> filters for missing fields

src/components/GuppyWrapper/index.jsx
example use case:
we need the number of subjects that don't have field `x` in the follow_up, including subjects that don't have a follow_up at all - this is possible by doing `(total number of subjects - number of follow_ups that have x)`
- use `termsNestedFields` instead of `missedNestedFields` in GuppyWrapper nested aggregation calls
=> fix(dat): use terms instead of missing

package-lock.json, package.json, src/components/ConnectedFilter/index.jsx, src/components/GuppyWrapper/index.jsx
https://ctds-planx.atlassian.net/browse/PXP-3968
- Bug: Sometimes, the download button in explorer (button type='data') is not disabled when viewing metadata or files the user does not have access to.
- Cause: Data from guppy is validated using the 'accessibleValidationField' in the guppy config, but the 'accessibleValidationField' was not always included by default in the data requested from guppy. If the 'accessibleValidationField' was not included, the data validation check that enables/disables the 'data' button would fail and default to 'enabled.'
- Fix: Always fetch 'accessibleValidationField' from guppy. This is done by always fetching the fields in 'accessibleFieldCheckList', which includes 'accessibleValidationField'.
Fix bug in Windmill explorer in which download buttons would …
=> Fix(PXP-3968): Fix explorer download button not disabled

src/components/GuppyWrapper/index.jsx
Jira: https://ctds-planx.atlassian.net/browse/PXP-4707?
Adds 'pending' state to buttons in Explorer when requests to Guppy are in flight.
Uses a combination of props passed from guppy and internal state in ExplorerButtonGroup to determine whether a request is in flight that will enable or disable the explorer's export / download buttons.
=> (PXP-4707) Add pending state to explorer buttons

Dockerfile
Resolves https://ctds-planx.atlassian.net/browse/PXP-5570 (Users see 0 projects in explorer)
This issue was caused by large session cookies set during NIH login causing request over 8kb in size being sent to guppy's nodejs server. This commit doubles guppy's request header size, which should prevent the problem from reoccuring.
- Increased node.js max header size to prevent issue with large NIH login session cookies hitting request header limit.
=> (PXP-5570) Bump header size limit to 16kb

src/server/__mocks__/mockDataFromES.js, src/server/auth/arboristClient.js
This PR fulfills https://ctds-planx.atlassian.net/browse/PXP-5773
Since Arborist now has policies for unauthenticated users, Guppy should now simply returns 401 if user doesn't have JWT.
This is achieved by changing the way that Guppy is interacting with the `/auth/resources` endpoint from `POST` to `GET`
Deployed to https://mingfei.planx-pla.net/
- Guppy will not always return 401 for user who doesn't have a JWT
=> PXP-5773 Fix/no jwt 401

README.md, devHelper/README.md, devHelper/docker/esearch.yml, devHelper/scripts/commands.sh, doc/queries.md, genData/genData.js, genData/types.js, genData/valueBank.json, generate_data.sh, package-lock.json, package.json, src/server/__mocks__/mockDataFromES.js, src/server/__mocks__/mockESData/mockNestedAggs.js, src/server/__mocks__/mockESData/mockNestedTermsAndMissingAggs.js, src/server/__tests__/schema.test.js, src/server/config.js, src/server/es/__tests__/aggs.test.js, src/server/es/aggs.js, src/server/es/const.js, src/server/es/index.js, src/server/resolvers.js, src/server/schema.js, src/server/utils/utils.js, stories/connectedTable.jsx
This PR fulfills https://ctds-planx.atlassian.net/browse/PXP-4737
Adding support to nested aggregations
Example query:
```
query: {
_aggregation: {
visits: {
visit_label: {
histogram: {
key
count
}
}
follow_ups: {
days_to_follow_up: {
histogram(rangeStep: 1) {
key
count
}
}
}
}
}
}
}
```
Result:
```
{
"data": {
"_aggregation": {
"subject": {
"visits": {
"visit_label": {
"histogram": [
{
"key": "vst_lbl_3",
"count": 29
},
...
]
},
"follow_ups": {
"days_to_follow_up": {
"histogram": [
{
"key": [
1,
2
],
"count": 21
},
...
]
}
}
}
}
}
}
}
```
Deployed at https://mingfei.planx-pla.net/query
- Supports aggregation on nested documents (nested aggregation)
- The current ES nested aggregation query syntax requires ES 6.7+ (note Guppy will not work for ES 7 yet)
=> PXP-4737 Feat/nested agg

doc/queries.md, package-lock.json, package.json, src/components/ConnectedFilter/index.jsx, src/components/ConnectedFilter/utils.js, src/components/GuppyWrapper/index.jsx, src/components/Utils/filters.js, src/components/Utils/queries.js, src/server/es/filter.js, src/server/resolvers.js, src/server/utils/utils.js, stories/downloadData.jsx
This PR fulfills https://ctds-planx.atlassian.net/browse/PXP-4733
Let filters in data explorer support nested fields
To add a nested field to filter, just denote it with a `.`
Example:
>       "filters": {
>         "tabs": [
>           {
>             "title": "Subject",
>             "fields": [
>               "project_id",               --> a regular field
>               "visits.visit_label"      --> a nested field
>             ]
>           }
>         ]
>       },
By default any `.` and/or `_` will be converted to whitespaces and the character immediately after that will be captialized, e.g.: `visits.visit_label` will be displayed as `Visits Visit Label`.
To overwrite, use `fieldMapping`,
Example:
>       "guppyConfig": {
>         "dataType": "subject",
>         "fieldMapping": …
=> PXP-4733 Feat/nested explorer filter

.pre-commit-config.yaml, package-lock.json, package.json, src/server/__mocks__/config.js, src/server/__mocks__/mockDataFromES.js, src/server/auth/__tests__/authHelper.test.js, src/server/auth/arboristClient.js, src/server/resolvers.js
Fulfills https://ctds-planx.atlassian.net/browse/PXP-6412
Deployed in: https://mingfei.planx-pla.net/ (should not see obvious changes)
- Switch Guppy from using Arborist's `/auth/resources` endpoint to `/auth/mapping` and filter out accessible list base on `read` access
- User can only see/query the data for a project if they have the following access: method `read` (or `*` - all methods) to service `guppy` (or `*` - all services) on that project resource. (previously they can see/query all the data if you any types of access to them)
=> PXP-6412 Feat/auth mapping

README.md, package-lock.json, package.json, src/components/ConnectedFilter/index.jsx, src/components/ConnectedFilter/utils.js, src/components/GuppyWrapper/index.jsx, src/components/Utils/queries.js
Jira Ticket: [PXP-6359](https://ctds-planx.atlassian.net/browse/PXP-6359)
- Adds a new filter type, `searchFilter`, to the available filters. Search Filters allow the user to search over fields which have too many options to be displayed normally -- for example, individual subject IDs or file GUIDs.
- To deploy SearchFilters in a tab of the Explorer page, add an entry to `data{/file}ExplorerConfig.filters.tabs.searchFields`. **NOTE: Do not add the same field to both `searchFields` and `fields`**, this will cause strange behavior in the search field. Example config: 
```
"filters": {
"tabs": [
{
"title": "Subject",
"searchFields": [
"subject_id",
"submitter_id",
"consent_codes"
],
"fields": [
"data_type",
"data_format",
...
]
}
```
=> (PXP-6359) Add Search Filter

TECHDEBT.md, doc/download.md, doc/queries.md, package-lock.json, package.json, src/components/GuppyWrapper/index.jsx, src/components/Utils/const.js, src/components/Utils/conversion.js, src/components/Utils/queries.js, src/server/__tests__/schema.test.js, src/server/resolvers.js, src/server/schema.js
See [Portal](https://github.com/uc-cdis/data-portal/pull/780) for remainder of PXP-6540 changes.
Due to Graphql limitations, see TECHDEBT.md for further details about this conversion service.
- Implemented new query argument "**format**" for Guppy to support TSV and CSV downloads from Explorer.
- Added Papaparse for conversion service
=> (PXP-6540): Feat/guppy format arg

package-lock.json, package.json, src/components/GuppyWrapper/index.jsx, src/components/Utils/queries.js
Make `format` to be optional in query strings issued by Guppy for backward compatibility, so newer Portal can work with old Guppy if don't need the export to CSV/TSV feature deployed
Companion PR: https://github.com/uc-cdis/data-portal/pull/790
- Make `format` to be optional in query strings issued by Guppy for backward compatibility
=> fix: make format arg optional from query lines

README.md, doc/docs:index_scoped_tiered_access.md, doc/index_scoped_tiered_access.md, src/server/__tests__/config.test.js, src/server/__tests__/schema.test.js, src/server/__tests__/testConfigFiles/test-index-scoped-tier-access.json, src/server/__tests__/testConfigFiles/test-invalid-index-scoped-tier-access.json, src/server/config.js, src/server/download.js, src/server/es/index.js, src/server/middlewares/authMiddleware/index.js, src/server/middlewares/authMiddleware/resolvers.js, src/server/middlewares/index.js, src/server/middlewares/perIndexTierAccessMiddleware/index.js, src/server/middlewares/tierAccessMiddleware/index.js, src/server/middlewares/tierAccessMiddleware/resolvers.js, src/server/resolvers.js, src/server/schema.js
This PR adds support for index-scoped tiered access settings in a manifest's guppy block. This refactor is backwards compatible with the older site-wide tiered-access level.
Jira Ticket: https://ctds-planx.atlassian.net/browse/HP-13
- Tiered-access settings can now be optionally specified at the index-level rather than the site-wide level. This change is backwards compatible with existing site-wide tiered-access settings. Specify index-scoped tiered-access settings in the guppy block of a common's manifest. See `doc/index_scoped_tiered_access.md` for more information.
=> feat: per-index tiered-access middleware

src/server/es/filter.js
When a nested filter is selected in the Exploration page and the aggregation on the same field is requested a null value is assigned to the nested query, which is not a permissible value in ES which returns 400.
- Fixed a bug causing incorrectly putting `null` into filters that contain nested fields
=> Fix nested query bug

.github/workflows/image_build_push.yaml, .travis.yml, Dockerfile
pin npm to 8.5 because npm 8.6 has introduced a bug in dependency resolution
use GH action to build images
=> chore: use npm 8.5 in travis and docker

src/components/Utils/queries.js
Catch error "cannot read property of undefined (reading '_aggregation')" and log it for easier debugging
- Catch errors while querying total counts
=> Catch errors while querying total counts

.eslintrc.js, devHelper/docker/es6.Dockerfile, devHelper/docker/esearch.yml, devHelper/scripts/commands.sh, package-lock.json, package.json, src/components/ConnectedFilter/index.jsx, src/components/ConnectedFilter/utils.js, src/components/GuppyWrapper/index.jsx, src/components/Utils/filters.js, src/components/Utils/queries.js, src/components/__tests__/filters.test.js, stories/conf.js
Jira Ticket: [MIDRC-390](https://ctds-planx.atlassian.net/browse/MIDRC-390)
See also https://github.com/uc-cdis/data-portal/pull/1404
- Add a new Guppy Explorer config field `filters.tabs.asTextAggFields` to explicitly specify the filter field names that to be casted from numeric to text 
- Fixed a bug that casts all numeric field in filter into text fields
- Update ES6 image for local dev helper to support running on Apple Silicon Macs
[MIDRC-390]: https://ctds-planx.atlassian.net/browse/MIDRC-390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MIDRC-390 fix separate fields

src/server/__mocks__/mockDataFromES.js, src/server/auth/arboristClient.js
Depends on https://github.com/uc-cdis/arborist/pull/163
Use POST instead of GET /auth/mapping endpoint to enable client_credentials authentication
=> PXP-11248 PXP-11258 using POST auth/mapping instead of GET to support client credentials authentication

Dockerfile, devHelper/README.md, src/server/middlewares/perIndexTierAccessMiddleware/index.js, src/server/middlewares/tierAccessMiddleware/index.js
- Fixed a bug causing tiered access middleware didn't properly applied to aggregation results
- **Important**: all envs that has tiered access enabled should deploy a Guppy that has this fix
=> fix apply hide number resolver to as text agg results

src/server/server.js
Param order was wrong on changed line, put err first.  Refer to: https://expressjs.com/en/guide/error-handling.html
Link to JIRA ticket if there is one: 
- Fixed param ordering in server start
=> Fix param ordering in server.js
