uc-cdis/guppy

- devHelper/scripts/commands.sh
- package-lock.json
- package.json
- src/server/config.js
- src/server/es/aggs.js
- src/server/es/filter.js
- src/server/logger.js
- src/server/middlewares/authMiddleware/arboristClient.js
- src/server/middlewares/authMiddleware/index.js
- src/server/middlewares/headerParser.js
- src/server/middlewares/index.js
- src/server/resolvers.js
- src/server/schema.js
- src/server/server.js
- src/server/utils.js
- Add auth middleware layer for resource access control
> feat(auth): add auth layer for resource control

- devHelper/scripts/commands.sh
- devHelper/scripts/generate_data.sh
- only generate data for jenkins and test projects
> fix(generate): only generate data for jenkins and test project

- devHelper/scripts/commands.sh
- devHelper/scripts/generate_data.sh
- src/server/config.js
- src/server/es/filter.js
- src/server/es/index.js
- src/server/schema.js
This PR change code to read array fields from config indices, and build array type schema
- Support array type
> feat(array): read array configs and build array type schema

- doc/TODO
- doc/queries.md
- src/components/Utils/queries.js
- src/server/resolvers.js
- src/server/schema.js
- change "size" arg to "first"
> fix(first): change "size" arg to "first"

- src/components/Utils/queries.js
- src/server/resolvers.js
- src/server/schema.js
- add _mapping schema for getting all fields
> feat(mapping): add _mapping schema for getting all fields

- src/components/Utils/queries.js
export function 'getGQLFilter'
> export getGQLFilter

- src/server/es/aggs.js
> fix(typo): fix scroll page size typo

- src/server/middlewares/tierAccessMiddleware/index.js
- src/server/resolvers.js
Fix some logic in tier access about accessable resource list
- Fix some logic in tier access about accessable resource list
> fix(filter): fix accessable resource logic for tier access

- src/components/Utils/queries.js
- src/server/config.js
- src/server/download.js
- src/server/es/aggs.js
- src/server/es/filter.js
- src/server/es/index.js
- src/server/middlewares/authMiddleware/index.js
- src/server/middlewares/tierAccessMiddleware/index.js
- src/server/resolvers.js
- src/server/schema.js
- src/server/utils/accessibilities.js
- src/server/utils/utils.js
- `accessibility` argument for aggregation query, only for regular tier access data commons
> feat(accessibility): add accessibility arg for aggregation in regular data commons

- src/server/config.js
- src/server/download.js
- src/server/middlewares/tierAccessMiddleware/index.js
- remove unused env var `projectField` from config
> fix(useless): remove useless env var

- README.md
- example_config.json
- src/server/config.js
- change all input configs to underscore style
> fix(camelCase): change all input configs to underscore style

- src/server/middlewares/tierAccessMiddleware/index.js
- in tier access middleware, we need to check "unaccessible" query when full data access
> fix(unaccessible): check "unaccessible" query when full data access

- devHelper/scripts/commands.sh
- src/server/config.js
- src/server/es/index.js
- src/server/logger.js
Change array config parser according to this tube commit https://github.com/uc-cdis/tube/pull/80/commits/755c62b93e92bb6eb8cee4360d9e100f712fe3eb
- Change array config parser to the format generated by tube
> fix(array): change arrange config parser, and some logger code

- README.md
- src/server/config.js
- src/server/es/aggs.js
Add customization and alias for missing data, instead of just ignoring it. 
- add customization and alias for missing data
> feat(missing): add customization and alias for missing data

- src/components/GuppyWrapper/index.jsx
- make accessible field list optional
> fix(optional): make accessible field optional

- package-lock.json
- package.json
> fix(version): to 0.1.1

- src/server/es/index.js
- deal with empty case for download's sort arg
> fix(sort): deal with empty case for download's sort arg

- package-lock.json
- package.json
update ui library to the version that fix for range slider
> fix(version): update version

- README.md
> add npm version badge

- package-lock.json
- package.json
- newer version fix charts and icon UI in Edge browser
> fix(ui): newer version fix charts and icon UI in Edge browser

- devHelper/README.md
- Add necessary environment variables to `npm start` command
> Update dev helper docs

- package-lock.json
- package.json
Update guppy version to `0.3.13`
> Update guppy version

- package-lock.json
- package.json
> update npm version to match github release

- src/components/ConnectedFilter/index.jsx
- src/components/GuppyWrapper/index.jsx
- src/components/Utils/filters.js
- src/server/es/index.js
- Add some error logs for easier debugging
> Error logs

- doc/download.md
- doc/queries.md
- package-lock.json
- package.json
- src/components/Utils/queries.js
- src/server/es/__tests__/sort.test.js
- src/server/es/index.js
- src/server/es/sort.js
- src/server/utils/utils.js
This is the accompanying PR of https://github.com/uc-cdis/data-portal/pull/689, which fulfills https://ctds-planx.atlassian.net/browse/PXP-5284
Let raw data query supports querying nested fields (for table in data explorer)
Let sort variable supports nested fields
Deployed in https://mingfei.planx-pla.net/ and https://qa-mickey.planx-pla.net/
- Let raw data query supports querying nested fields (for table in data explorer)
- Let sort variable supports nested fields
> PXP-5284 Feat/nested table

- package-lock.json
- package.json
- src/components/ConnectedFilter/index.jsx
- src/components/Utils/filters.js
- src/components/__tests__/filters.test.js
- stories/conf.js
- stories/connectedFilter.jsx
This PR fulfills https://occ-data.atlassian.net/browse/COV-369 and https://ctds-planx.atlassian.net/browse/PXP-6043
Related to: https://github.com/uc-cdis/gen3-ui-component/pull/73 and https://github.com/uc-cdis/data-portal/pull/701
- Adopted all-new gen3-ui-component with completely refreashed filter components
- Fixed a problem causing `RangeFilter` upper and lower bounds not get updated correctly
- Gen3-ui-component: bump to 0.5.4
> COV-369 PXP-6043 Feat/new ui lib

- doc/queries.md
- src/components/Utils/queries.js
- src/server/download.js
- src/server/middlewares/tierAccessMiddleware/index.js
This PR fulfills https://ctds-planx.atlassian.net/browse/PXP-6510
Modify Guppy to NOT return a list of out-of-scope resources in its response if users are trying to query something that they don't have access to, since those information could be confidential.
Try at: https://mingfei.planx-pla.net/query
- Guppy will NOT return the list of out-of-scope resources in its response to the public
- The list of out-of-scope resources will be printed into logs
> PXP-6510 Fix/log

- src/server/__tests__/schema.test.js
- src/server/resolvers.js
- src/server/schema.js
- src/server/utils/utils.js
- Added searchInput parameter to mapping schema to query attribute names.
> mapping supports searchInput parameter using JS regex

- package-lock.json
- package.json
[PXP-6221](https://ctds-planx.atlassian.net/browse/PXP-6221) update in @gen3/ui-component
- feat/comma-numbers: filters and charts updated helper function refactored to use built in js function
Update @gen3/ui-component dependency to version 0.6.3
> (PXP-6221): Feat/UI component update

- package-lock.json
- package.json
update in @gen3/ui-component
* [PXP-7435](https://ctds-planx.atlassian.net/browse/PXP-7435) add overflow wrap for long words
* [PXP-7378 ](https://ctds-planx.atlassian.net/browse/PXP-7378) add full-pie chart type support
Update @gen3/ui-component dependency to version 0.6.5
> (PXP-7435): Feat/UI component update

- package-lock.json
- package.json
- src/components/ConnectedFilter/index.jsx
Jira Ticket: [PXP-7760](https://ctds-planx.atlassian.net/browse/PXP-7760)
- add hideEmptyFilterSection flag and functionality to hide empty filter sections 
- add handling of edge case where tab will have no visible filters
Update @gen3/ui-component dependency to version 0.7.0
> (PXP-7760): Feat/remove empty field lists

- package-lock.json
- package.json
> chore: update npm version

- genData/genData.js
- package-lock.json
- package.json
- src/components/ConnectedFilter/index.jsx
- src/components/ConnectedFilter/utils.js
- stories/connectedFilter.jsx
Jira Ticket: [COV-816](https://occ-data.atlassian.net/browse/COV-816)
- add flag for inclusion in filters of missing data category 
- change test data generating script to also generate missing data fields
> (COV-816): feat/missingDataFiltersFlag2: add missing data flag for inclusion in filters

- src/components/GuppyWrapper/index.jsx
- The download format check is now case insensitive
> Fix format console error

- src/server/auth/authHelper.js
- src/server/es/index.js
- Add debug logs to `initialize()` and `query()` functions
> Add debug logs

- devHelper/docker/esearch.yml
- Fixed a bug causing some env vars didn't get passed into dev container correctly
> fix: dev docker compose env vars

- devHelper/docker/esearch.yml
- src/components/Utils/queries.js
- src/server/es/__tests__/aggs.test.js
- src/server/es/aggs.js
- src/server/schema.js
Jira Ticket: [PXP-4614](https://ctds-planx.atlassian.net/browse/PXP-4614)
add total terms count to parent termsFields
> (PXP-4614): feat/aggregationTermsCount: add total terms count to parent termsFields

- src/components/Utils/queries.js
- src/server/es/index.js
Jira Ticket: [PXP-9964](https://ctds-planx.atlassian.net/browse/PXP-9964)
* fix field check to also search for sub categories using dot separated field names
* fix lint error in queries file
> (PXP-9964): fix/setupNestedArrayFields: fix field check

- src/server/es/index.js
Jira Ticket: [PXP-9147](https://ctds-planx.atlassian.net/browse/PXP-9147)
- speed up _totalCount by not pulling data only total
[PXP-9147]: https://ctds-planx.atlassian.net/browse/PXP-9147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (PXP-9147): fix/countSpeed: speed up _totalCount by not pulling data only total

- .github/labeler.yml
> Fix the auto label

- .travis.yml
- Dockerfile
- update node to 16 for future dependency updates 
- update node from 14 to 16
> update node to 16

- devHelper/README.md
- Add note to documentation for Ubuntu generate_data not running correctly
> Add note to documentation for Ubuntu generate_data not running correctly

- devHelper/scripts/commands.sh
- package-lock.json
- package.json
- src/components/ConnectedFilter/index.jsx
- src/components/ConnectedFilter/utils.js
- src/components/GuppyWrapper/index.jsx
- src/components/Utils/queries.js
Jira Ticket: [PPS-588](https://ctds-planx.atlassian.net/browse/PPS-588)
- Guppy will send CSRF token in request headers if available
- Remove unused dep `csurf`
[PPS-588]: https://ctds-planx.atlassian.net/browse/PPS-588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PPS-588 Fix/csrf

- src/server/es/index.js
- Improved logging for GraphQL queries (include timing)
> chore(logging): add time to graphql log

- package-lock.json
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/PPS-1675
- update cross-spawn
> PPS-1675 update cross-spawn
